// City data

const cityData = reactive({
  'san-francisco': {
    name: 'San Francisco',
    location: 'California, United States',
    weather: {
      temperature: '72°F',
      condition: 'Sunny',
      description: 'Clear skies',
      feelsLike: '75°F',
      humidity: '65%',
      windSpeed: '7 mph',
    },
    forecast: [
      {
        day: 'Today',
        date: 'Dec 19',
        iconUrl: '../media/sunny.png',
        temperature: '72°F',
        condition: 'Sunny',
        range: 'H: 75°F L: 58°',
      },
      {
        day: 'Tomorrow',
        date: 'Dec 20',
        icon: '⛅',
        temperature: '68°F',
        condition: 'Partly Cloudy',
        range: 'H: 71° L: 55°',
      },
      {
        day: 'Saturday',
        date: 'Dec 21',
        icon: '🌧️',
        temperature: '63°F',
        condition: 'Light Rain',
        range: 'H: 66° L: 52°',
      },
      {
        day: 'Sunday',
        date: 'Dec 22',
        icon: '☁️',
        temperature: '65°F',
        condition: 'Cloudy',
        range: 'H: 68° L: 54°',
      },
      {
        day: 'Monday',
        date: 'Dec 23',
        icon: '☀️',
        temperature: '70°F',
        condition: 'Sunny',
        range: 'H: 73° L: 56°',
      },
    ],
  },
  'boston': {
    name: 'Boston',
    location: 'Massachusetts, United States',
    weather: {
      temperature: '45°F',
      condition: 'Overcast',
      description: 'Cloudy skies',
      feelsLike: '42°F',
      humidity: '78%',
      windSpeed: '12 mph',
    },
    forecast: [
      {
        day: 'Today',
        date: 'Dec 19',
        icon: '☁️',
        temperature: '45°F',
        condition: 'Overcast',
        range: 'H: 48° L: 35°',
      },
      {
        day: 'Tomorrow',
        date: 'Dec 20',
        icon: '🌨️',
        temperature: '38°F',
        condition: 'Snow',
        range: 'H: 42° L: 28°',
      },
      {
        day: 'Saturday',
        date: 'Dec 21',
        icon: '❄️',
        temperature: '32°F',
        condition: 'Heavy Snow',
        range: 'H: 35° L: 22°',
      },
      {
        day: 'Sunday',
        date: 'Dec 22',
        icon: '⛅',
        temperature: '40°F',
        condition: 'Partly Cloudy',
        range: 'H: 43° L: 30°',
      },
      {
        day: 'Monday',
        date: 'Dec 23',
        icon: '☀️',
        temperature: '48°F',
        condition: 'Sunny',
        range: 'H: 52° L: 38°',
      },
    ],
  },
  'seattle': {
    name: 'Seattle',
    location: 'Washington, United States',
    weather: {
      temperature: '52°F',
      condition: 'Rainy',
      description: 'Light drizzle',
      feelsLike: '48°F',
      humidity: '85%',
      windSpeed: '8 mph',
    },
    forecast: [
      {
        day: 'Today',
        date: 'Dec 19',
        icon: '🌧️',
        temperature: '52°F',
        condition: 'Rainy',
        range: 'H: 55° L: 45°',
      },
      {
        day: 'Tomorrow',
        date: 'Dec 20',
        icon: '⛅',
        temperature: '49°F',
        condition: 'Partly Cloudy',
        range: 'H: 53° L: 42°',
      },
      {
        day: 'Saturday',
        date: 'Dec 21',
        icon: '🌧️',
        temperature: '46°F',
        condition: 'Heavy Rain',
        range: 'H: 50° L: 40°',
      },
      {
        day: 'Sunday',
        date: 'Dec 22',
        icon: '☁️',
        temperature: '50°F',
        condition: 'Cloudy',
        range: 'H: 54° L: 43°',
      },
      {
        day: 'Monday',
        date: 'Dec 23',
        icon: '🌧️',
        temperature: '48°F',
        condition: 'Light Rain',
        range: 'H: 52° L: 41°',
      },
    ],
  },
  'chicago': {
    name: 'Chicago',
    location: 'Illinois, United States',
    weather: {
      temperature: '28°F',
      condition: 'Snow',
      description: 'Heavy snowfall',
      feelsLike: '18°F',
      humidity: '92%',
      windSpeed: '15 mph',
    },
    forecast: [
      {
        day: 'Today',
        date: 'Dec 19',
        icon: '🌨️',
        temperature: '28°F',
        condition: 'Snow',
        range: 'H: 32° L: 20°',
      },
      {
        day: 'Tomorrow',
        date: 'Dec 20',
        icon: '❄️',
        temperature: '22°F',
        condition: 'Blizzard',
        range: 'H: 26° L: 15°',
      },
      {
        day: 'Saturday',
        date: 'Dec 21',
        icon: '☁️',
        temperature: '35°F',
        condition: 'Cloudy',
        range: 'H: 38° L: 28°',
      },
      {
        day: 'Sunday',
        date: 'Dec 22',
        icon: '⛅',
        temperature: '42°F',
        condition: 'Partly Cloudy',
        range: 'H: 45° L: 35°',
      },
      {
        day: 'Monday',
        date: 'Dec 23',
        icon: '☀️',
        temperature: '38°F',
        condition: 'Sunny',
        range: 'H: 42° L: 30°',
      },
    ],
  },
  'new-york': {
    name: 'New York',
    location: 'New York, United States',
    weather: {
      temperature: '39°F',
      condition: 'Partly Cloudy',
      description: 'Mix of sun and clouds',
      feelsLike: '34°F',
      humidity: '68%',
      windSpeed: '10 mph',
    },
    forecast: [
      {
        day: 'Today',
        date: 'Dec 19',
        icon: '⛅',
        temperature: '39°F',
        condition: 'Partly Cloudy',
        range: 'H: 43° L: 32°',
      },
      {
        day: 'Tomorrow',
        date: 'Dec 20',
        icon: '🌧️',
        temperature: '42°F',
        condition: 'Light Rain',
        range: 'H: 46° L: 36°',
      },
      {
        day: 'Saturday',
        date: 'Dec 21',
        icon: '☁️',
        temperature: '45°F',
        condition: 'Cloudy',
        range: 'H: 48° L: 38°',
      },
      {
        day: 'Sunday',
        date: 'Dec 22',
        icon: '⛅',
        temperature: '47°F',
        condition: 'Partly Cloudy',
        range: 'H: 51° L: 40°',
      },
      {
        day: 'Monday',
        date: 'Dec 23',
        icon: '☀️',
        temperature: '52°F',
        condition: 'Sunny',
        range: 'H: 55° L: 45°',
      },
    ],
  },
})
